In [73]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)

In [74]:
# download csv from url
url = 'https://archives.nseindia.com/content/indices/ind_nifty100list.csv' # Nifty 100 stocks
nifty100 = pd.read_csv(url)
nifty100.to_csv('ind_nifty100list.csv', index=False)
symbol= pd.read_csv("ind_nifty100list.csv")  # read csv file
symbol["ticker"] = symbol["Symbol"] + ".NS"
ticker= symbol['ticker'].values.tolist() # convert to list
sd = yf.download(ticker, interval='1d')['Close'] # download data from yahoo finance
sd

[*********************100%***********************]  100 of 100 completed

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TCS.NS,TECHM.NS,TITAN.NS,TORNTPHARM.NS,ULTRACEMCO.NS,UPL.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZOMATO.NS
Date,,,,,,,,,,,,,,,,,,,,,
1995-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-22,4270.500000,1831.750000,2397.250000,974.849976,745.599976,804.400024,444.850006,5066.000000,3248.050049,655.150024,...,3238.500000,1119.050049,2970.250000,1862.650024,8162.750000,674.400024,803.549988,280.649994,382.299988,74.349998
2023-06-23,4239.700195,1766.900024,2233.550049,959.849976,714.299988,757.500000,425.799988,5045.450195,3297.699951,634.299988,...,3216.350098,1115.500000,2939.149902,1863.050049,8080.200195,666.849976,766.099976,276.200012,379.950012,74.150002
2023-06-26,4285.350098,1792.300049,2295.600098,968.450012,724.400024,770.750000,432.049988,5036.950195,3308.149902,644.000000,...,3189.649902,1111.900024,2972.600098,1867.750000,8167.100098,679.200012,799.200012,279.799988,380.899994,74.849998
2023-06-27,4294.500000,1788.599976,2284.449951,959.549988,720.250000,773.200012,433.850006,5142.799805,3326.000000,641.500000,...,3197.350098,1119.699951,2975.699951,1879.050049,8208.500000,674.349976,799.400024,279.549988,382.600006,76.150002
2023-06-30,4423.000000,1813.699951,2388.050049,945.900024,739.250000,767.250000,425.899994,5098.200195,3362.050049,654.599976,...,3302.250000,1130.849976,3047.649902,1904.949951,8294.750000,687.549988,802.549988,277.950012,389.149994,75.050003

In [75]:
current_date = (pd.to_datetime('today') - pd.Timedelta(days=1500)).strftime('%Y-%m-%d')  # 1460 days = 4 years
sd1 = sd[sd.index > current_date] # filter data for last 4 years
# drop columns with all NaN values
sd1.dropna(axis=1, how='any', inplace=True)
sd1_columns =sd1.columns # get column names
sd1

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,TORNTPHARM.NS,ULTRACEMCO.NS,UPL.NS,VBL.NS,VEDL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2019-05-24,1496.949951,1704.900024,156.399994,42.299999,410.250000,227.500000,231.649994,1170.500000,1384.500000,136.000000,...,48.415001,2048.000000,735.849976,1219.900024,764.224976,4800.100098,680.566650,137.785187,163.899994,282.899994
2019-05-27,1613.300049,1759.800049,157.199997,43.150002,412.399994,222.600006,239.149994,1198.800049,1366.849976,143.250000,...,51.255001,2055.149902,726.049988,1240.949951,755.500000,4841.049805,682.966675,138.437042,166.500000,280.500000
2019-05-28,1594.500000,1750.699951,157.649994,45.000000,412.649994,241.550003,238.399994,1190.800049,1364.349976,163.250000,...,50.705002,2073.750000,737.150024,1231.550049,761.750000,4772.950195,677.033325,140.325928,169.550003,282.950012
2019-05-29,1587.900024,1721.550049,155.149994,44.700001,406.549988,236.699997,233.850006,1203.300049,1358.250000,167.750000,...,49.330002,2107.550049,738.849976,1234.650024,755.474976,4719.850098,664.666687,139.866669,165.850006,285.700012
2019-05-30,1574.300049,1708.150024,158.100006,44.599998,409.299988,233.750000,233.000000,1203.000000,1374.599976,171.149994,...,48.794998,2146.300049,735.000000,1240.599976,781.500000,4758.899902,670.566650,136.422226,164.000000,288.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-22,4270.500000,1831.750000,2397.250000,974.849976,745.599976,804.400024,444.850006,5066.000000,3248.050049,655.150024,...,111.099998,3238.500000,1119.050049,2970.250000,1862.650024,8162.750000,674.400024,803.549988,280.649994,382.299988
2023-06-23,4239.700195,1766.900024,2233.550049,959.849976,714.299988,757.500000,425.799988,5045.450195,3297.699951,634.299988,...,109.599998,3216.350098,1115.500000,2939.149902,1863.050049,8080.200195,666.849976,766.099976,276.200012,379.950012
2023-06-26,4285.350098,1792.300049,2295.600098,968.450012,724.400024,770.750000,432.049988,5036.950195,3308.149902,644.000000,...,109.849998,3189.649902,1111.900024,2972.600098,1867.750000,8167.100098,679.200012,799.200012,279.799988,380.899994
2023-06-27,4294.500000,1788.599976,2284.449951,959.549988,720.250000,773.200012,433.850006,5142.799805,3326.000000,641.500000,...,110.750000,3197.350098,1119.699951,2975.699951,1879.050049,8208.500000,674.349976,799.400024,279.549988,382.600006
2023-06-30,4423.000000,1813.699951,2388.050049,945.900024,739.250000,767.250000,425.899994,5098.200195,3362.050049,654.599976,...,112.000000,3302.250000,1130.849976,3047.649902,1904.949951,8294.750000,687.549988,802.549988,277.950012,389.149994

In [76]:
def momentum_ratio(df): # function to calculate momentum ratio
    for i in df.columns:
        returns252 = df[i].pct_change(periods=252) # percent change over 252 trading days
        stds252 = returns252.rolling(window=252).std() # standard deviation over 252 trading days
        returns126 = df[i].pct_change(periods=126) # percent change over 126 trading days
        stds126 = returns126.rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'_Year_momentum'] = returns252/stds252 # momentum ratio for 252 trading days
        df[i+'_6_month_momentum'] = returns126/stds126 # momentum ratio for 126 trading days
    df.dropna(inplace=True) # drop rows with NaN values
    return df

momentum_df = momentum_ratio(sd1)

In [77]:
momentum_df

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,ULTRACEMCO.NS_Year_momentum,ULTRACEMCO.NS_6_month_momentum,UPL.NS_Year_momentum,UPL.NS_6_month_momentum,VBL.NS_Year_momentum,VBL.NS_6_month_momentum,VEDL.NS_Year_momentum,VEDL.NS_6_month_momentum,WIPRO.NS_Year_momentum,WIPRO.NS_6_month_momentum
Date,,,,,,,,,,,,,,,,,,,,,
2021-06-07,1685.650024,2045.949951,1624.300049,1264.849976,878.599976,1589.449951,339.049988,3315.300049,2933.100098,1626.949951,...,2.041298,2.783028,2.149353,3.566159,3.794988,4.246724,1.697240,2.610260,2.573915,3.683413
2021-06-08,1680.250000,2042.650024,1636.449951,1267.550049,874.200012,1592.599976,340.350006,3289.449951,2926.250000,1640.849976,...,1.927062,2.675501,1.985558,3.382732,3.404293,3.444485,1.623506,2.444964,2.541084,3.560247
2021-06-09,1674.849976,2004.400024,1594.650024,1239.150024,852.599976,1571.500000,334.350006,3305.899902,2943.550049,1588.199951,...,1.988596,2.665717,1.962052,3.079336,3.753974,4.373750,1.596347,2.328345,2.350419,3.404053
2021-06-10,1671.349976,2030.300049,1612.000000,1233.500000,846.750000,1589.900024,341.549988,3325.699951,2950.600098,1594.050049,...,1.963087,2.260713,1.977803,2.975471,3.861035,5.067632,1.622221,2.279888,2.574701,3.585393
2021-06-11,1648.550049,2024.500000,1601.599976,1217.699951,839.750000,1602.599976,337.700012,3336.550049,2956.250000,1626.199951,...,1.930949,2.257411,2.004224,2.649296,3.903031,4.594442,1.627671,2.264231,2.599585,3.663342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-22,4270.500000,1831.750000,2397.250000,974.849976,745.599976,804.400024,444.850006,5066.000000,3248.050049,655.150024,...,3.005445,2.210644,-0.174254,-1.475887,4.558706,0.864777,0.486771,-0.597695,-1.063773,-0.502880
2023-06-23,4239.700195,1766.900024,2233.550049,959.849976,714.299988,757.500000,425.799988,5045.450195,3297.699951,634.299988,...,3.078760,2.073690,0.033118,-1.390765,4.510922,0.659090,0.455728,-0.638640,-0.688595,-0.669682
2023-06-26,4285.350098,1792.300049,2295.600098,968.450012,724.400024,770.750000,432.049988,5036.950195,3308.149902,644.000000,...,2.876832,2.676346,0.789615,-1.215556,4.936401,1.112777,2.056325,-0.429818,-0.887969,-0.638503
2023-06-27,4294.500000,1788.599976,2284.449951,959.549988,720.250000,773.200012,433.850006,5142.799805,3326.000000,641.500000,...,2.751301,2.658442,0.404815,-0.920691,5.177000,1.108015,1.738462,-0.415519,-1.081340,-0.458918
2023-06-30,4423.000000,1813.699951,2388.050049,945.900024,739.250000,767.250000,425.899994,5098.200195,3362.050049,654.599976,...,2.812689,3.166669,1.591443,-0.413315,5.154637,1.773454,2.313864,-0.142321,-0.571685,0.871794

In [78]:
def Calculate_Z_Score(df,columns=sd1_columns):
    for i in columns:  # calculate z score for each stock
        mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
        std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
        df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
        mean126 = df[i+'_6_month_momentum'].rolling(window=126).mean() # mean over 126 trading days
        std126 = df[i+'_6_month_momentum'].rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'6_month_Z_Score'] = (df[i]-mean126)/std126 # z score for 126 trading days
        df[i+'Z_Score'] = (df[i+'Year_Z_Score'] + df[i+'6_month_Z_Score'])/2 # average z score (weighted average)
    df.dropna(inplace=True) # drop rows with NaN values
    return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,UPL.NSZ_Score,VBL.NSYear_Z_Score,VBL.NS6_month_Z_Score,VBL.NSZ_Score,VEDL.NSYear_Z_Score,VEDL.NS6_month_Z_Score,VEDL.NSZ_Score,WIPRO.NSYear_Z_Score,WIPRO.NS6_month_Z_Score,WIPRO.NSZ_Score
Date,,,,,,,,,,,,,,,,,,,,,
2022-06-09,2352.399902,2138.100098,2219.199951,1812.650024,735.500000,2116.500000,365.299988,3670.050049,2686.800049,2498.050049,...,1297.428696,533.086474,437.351007,485.218741,507.493108,213.250608,360.371858,493.524041,400.687479,447.105760
2022-06-10,2333.350098,2135.399902,2203.100098,1757.599976,726.400024,2051.899902,365.149994,3700.500000,2708.750000,2398.300049,...,1266.548426,546.862267,440.201873,493.532070,499.197840,209.942962,354.570401,475.830343,389.321033,432.575688
2022-06-13,2337.449951,2121.250000,2079.750000,1798.699951,695.250000,2051.899902,362.700012,3651.899902,2660.750000,2337.550049,...,1241.351099,543.639589,433.050254,488.344922,474.704352,199.290136,336.997244,457.380233,376.952887,417.166560
2022-06-14,2321.350098,2116.100098,2196.449951,1788.750000,704.700012,2057.500000,359.549988,3706.199951,2635.399902,2374.699951,...,1211.567424,565.669276,438.190614,501.929945,472.140077,197.831666,334.985872,454.003133,377.233963,415.618548
2022-06-15,2304.699951,2122.649902,2184.600098,1757.849976,703.750000,2057.300049,361.950012,3722.699951,2661.149902,2351.800049,...,1194.062297,579.371413,435.793977,507.582695,467.645976,195.480280,331.563128,445.242626,372.423293,408.832959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-22,4270.500000,1831.750000,2397.250000,974.849976,745.599976,804.400024,444.850006,5066.000000,3248.050049,655.150024,...,935.275518,961.904355,658.347948,810.126151,551.201029,327.305963,439.253496,696.866733,968.629241,832.747987
2023-06-23,4239.700195,1766.900024,2233.550049,959.849976,714.299988,757.500000,425.799988,5045.450195,3297.699951,634.299988,...,926.192221,927.912012,644.700913,786.306462,539.808554,321.916613,430.862583,693.249728,962.164587,827.707158
2023-06-26,4285.350098,1792.300049,2295.600098,968.450012,724.400024,770.750000,432.049988,5036.950195,3308.149902,644.000000,...,943.434254,981.140635,692.917571,837.029103,523.095497,330.800573,426.948035,696.504557,964.567692,830.536124
2023-06-27,4294.500000,1788.599976,2284.449951,959.549988,720.250000,773.200012,433.850006,5142.799805,3326.000000,641.500000,...,937.169700,995.061622,721.686996,858.374309,506.764070,333.626342,420.195206,701.693472,972.564228,837.128850
2023-06-30,4423.000000,1813.699951,2388.050049,945.900024,739.250000,767.250000,425.899994,5098.200195,3362.050049,654.599976,...,947.414740,1012.747770,743.656356,878.202063,481.237962,335.450325,408.344143,713.966042,947.371843,830.668942